### ISSUE TITLE
Delegate geoecoding

### ISSUE THREAD

**Issue by migurski** [OpenPrecincts/voterroll-geocode#5]
Can I recommend using a service like Geocode.earth or similar instead of writing our own geocoding? It’s a rabbithole all on its own.

**Comment by jamesturk** [comment]
We definitely aren't planning on writing our own geocoder :) . Right now
the team had been using the census geocoder since we need the block level
results but planning to evaluate some other options as we move forward.

**Comment by migurski** [comment]
Okay, phew. :)
